### ISSUE TITLE
Win系统下无法检测到已安装的lgr

### ISSUE THREAD

**Issue by TogetsuDo** [Lonely-Sails/nonebot-plugin-lagrange#1]
![478cdc7144c875a1a43b89af0d27226a](https://github.com/user-attachments/assets/7da15b20-74d4-4f40-88be-5bb45c07f044)
![394e5afa204427d4f821b38c05502b22](https://github.com/user-attachments/assets/59af2a57-2984-4d10-bc58-9a98a8c3fee8)
能够创建bin文件却无法遍历到lgr本体

**Comment by Lonely-Sails** [comment]
安装失败是由于使用代理炸了（）现已修复。
